### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by hitchhicker007** [hitchhicker007/tic_tac_toe#1]
- Add installation steps properly. 
- Add a small description of the code and libraries which have been used in the project.

**Comment by isaacmtp** [comment]
please i'll do that

**Comment by hitchhicker007** [comment]
@isaacmtp I'm assigning this task to you.

**Comment by issac5693** [comment]
Cool mate

**Comment by Abhay5855** [comment]
Cam you please assign me this issue?

**Comment by hitchhicker007** [comment]
> Cam you please assign me this issue?

Hello @Abhay5855, I assign issues on a first come first serve basis. If @isaacmtp will not be able to do this task in the next 3 days then I'll assign it to you.

**Comment by hitchhicker007** [comment]
@Abhay5855 I've assigned this issue to you also. best of luck :+1:

**Comment by Abhay5855** [comment]
@hitchhicker007started working on it will give update soon

**Comment by hitchhicker007** [comment]
@Abhay5855 make sure you follow [contributing.md](https://github.com/hitchhicker007/tic_tac_toe/blob/master/contributing.md)

**Comment by Abhay5855** [comment]
@hitchhicker007 Hey I have made the changes as requested in the issue can you check the Pull request

**Comment by Abhay5855** [comment]
@hitchhicker007 Thanks for showing trust and accepting my Pull request

**Comment by hitchhicker007** [comment]
@Abhay5855 TY for your contribution. make sure you star this repo and share it with your friends.
