### ISSUE TITLE
Change GUI of application

### ISSUE THREAD

**Issue by hitchhicker007** [hitchhicker007/tic_tac_toe#6]
only change the GUI of the first screen of an application where the user selects a mode of gameplay.

you can make it more attractive according to your creativity.

**Comment by programmerraja** [comment]
Could i work on this?

**Comment by hitchhicker007** [comment]
@programmerraja here you go

**Comment by Nivedita1103** [comment]
hey! I would like to contribute to the issue.

**Comment by hitchhicker007** [comment]
@Nivedita1103 this issue is already been solved, I'm going to add some more issues. you can contribute to it.
